### ISSUE TITLE
Not working...maybe a Cmd-4 conflict

### ISSUE THREAD

**Issue by rdell** [Arkkimaagi/ArtboardZoom#17]
I've uninstalled and reinstalled this plugin a few times and it still does not work in Sketch 48.2 (47327). I thought maybe it was a keyboard conflict with Outlook or some other app, but further testing did not reveal any conflicts. Not sure why it's not working. I used to use the crap out of this plugin because it's so great, but now I've been reduced to using Cmd-2, which doesn't quite cut it.

Any thoughts?

thanks,
-rob

**Comment by Arkkimaagi** [comment]
I will take a look at it after new year has passed. Meanwhile you can take a look at the sourcecode that you absolutely have the latest version.

**Comment by Arkkimaagi** [comment]
Okay, I'm sorry, this was my bad.

The version release workflow is a bit complex and I had forgotten to do it fully. This is why Sketch was not getting the proper version automatically. Now it is fixed and you should get the latest 1.2.3 updated automatically.

After it has been updated, checking the "About ArtboardZoom" dialog should show the correct version like this:
![image](https://user-images.githubusercontent.com/1191667/34477629-2d6abc92-efa4-11e7-9311-196d4eaee629.png)

I will now document the workflow, so that I do not forget it in the future.

I'm sorry for all this trouble and I hope you enjoy using the plugin in the future too.

**Comment by Arkkimaagi** [comment]
If you can verify that it works, you or I can then close this issue.

**Comment by rdell** [comment]
I appreciate your diligence.
Love the plugin!



thanks,
rob
---
Robert Dell'Aquila
Thumpwerks, Inc.
c: 847-309-4658
e: rob@thumpwerks.com

**Comment by Arkkimaagi** [comment]
So, did you get it working?

**Comment by rdell** [comment]
Yes, I did.
Thanks again for your diligence.



thanks,
rob
---
Robert Dell'Aquila
Thumpwerks, Inc.
c: 847-309-4658
e: rob@thumpwerks.com

**Comment by Arkkimaagi** [comment]
Closing the issue as solved. Thanks for the report!
